# Generated by Django 5.2.1 on 2025-05-22 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_novels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novel',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/covers/'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Đang tiến hành'), ('completed', 'Hoàn thành')], default='ongoing', max_length=10),
        ),
    ]
