# Generated by Django 5.2.1 on 2025-05-22 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='novelupload',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='novelupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genreselection',
            name='novel_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_selections', to='uploads.novelupload'),
        ),
        migrations.AddField(
            model_name='chapterupload',
            name='novel_upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='uploads.novelupload'),
        ),
        migrations.AlterUniqueTogether(
            name='genreselection',
            unique_together={('novel_upload', 'genre')},
        ),
        migrations.AlterUniqueTogether(
            name='chapterupload',
            unique_together={('novel_upload', 'chapter_number')},
        ),
    ]
