# Generated by Django 5.2.1 on 2025-05-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelupload',
            name='user',
        ),
        migrations.AddField(
            model_name='novelupload',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='novel_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='novelupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='chapterupload',
            unique_together={('novel_upload', 'chapter_number')},
        ),
    ]
